import type { AppState, Transaction } from './types'
import {
  REASON_LABELS,
  movementSummary,
  siteLabel,
  transactionLabel,
  transactionLoss,
} from './types'
import { formatWeight, kgToDisplay } from './units'
import { formatStampedTime, localDateTimeInput } from './datetime'
import { profileFor } from './compliance'

// The business identity lines (name + ABN + RTA), preferring the values
// frozen on the row, falling back to current settings.
function businessLines(t: Transaction, state: AppState): string[] {
  const profile = profileFor(state.jurisdiction)
  const abn = t.businessAbn || state.businessAbn
  const auth = t.arcAuthorisationNumber || state.arcAuthorisationNumber
  return [
    t.businessName || state.businessName,
    abn ? `${profile.businessNumberShort} ${abn}` : '',
    auth ? `${profile.businessAuthShort} ${auth}` : '',
  ].filter(Boolean)
}

// The per-job detail block (no business header / footer) — the lines that
// describe one transaction. Reused for a single record and for a day
// bundle. Prefers live records, falls back to the values frozen on the row.
function jobBlock(t: Transaction, state: AppState): string[] {
  const { bottles, sites, units, transactions, unit, clock, jurisdiction } = state
  const profile = profileFor(jurisdiction)
  const tz = state.location.timezone

  const bottle = bottles.find((b) => b.id === t.bottleId)
  const sourceBottle = t.sourceBottleId
    ? bottles.find((b) => b.id === t.sourceBottleId)
    : undefined
  const site = sites.find((s) => s.id === t.siteId)
  const txUnit = units.find((u) => u.id === t.unitId)
  const move = movementSummary(t, transactions, (id) =>
    sites.find((s) => s.id === id)?.name,
  )
  const loss = transactionLoss(t)

  const amount = t.amount > 0 ? formatWeight(t.amount, unit) : ''
  const refrigerant = bottle?.refrigerantType ?? ''
  const siteName = site ? siteLabel(site) : t.siteName

  const equipName = txUnit?.name ?? t.unitName ?? t.equipment ?? ''
  const equipExtra = txUnit
    ? [
        [txUnit.manufacturer, txUnit.model].filter(Boolean).join(' '),
        txUnit.serial ? `S/N ${txUnit.serial}` : '',
      ]
        .filter(Boolean)
        .join(', ')
    : ''
  const equipment = equipName
    ? equipExtra
      ? `${equipName} (${equipExtra})`
      : equipName
    : ''

  const techLine =
    t.technician || t.technicianLicence
      ? [
          t.technician,
          t.technicianLicence
            ? `${profile.techLicenceShort} ${t.technicianLicence}`
            : '',
        ]
          .filter(Boolean)
          .join(' · ')
      : ''

  return [
    `${transactionLabel(t.kind)}${amount ? ` — ${amount}` : ''}${refrigerant ? ` ${refrigerant}` : ''}`,
    formatStampedTime(t.date, t.tz, tz, clock),
    siteName ? `Site: ${siteName}` : '',
    site?.address ? `Address: ${site.address}` : '',
    site?.client ? `Client: ${site.client}` : '',
    equipment ? `Equipment: ${equipment}` : '',
    bottle ? `Bottle: ${bottle.bottleNumber} (${bottle.refrigerantType})` : '',
    sourceBottle ? `From bottle: ${sourceBottle.bottleNumber}` : '',
    move ? `Movement: ${move.from} → ${move.to}` : '',
    t.amount > 0
      ? `Bottle gross: ${kgToDisplay(t.weightBefore, unit).toFixed(2)} → ${formatWeight(t.weightAfter, unit)}`
      : '',
    loss > 0 ? `Loss: ${formatWeight(loss, unit)}` : '',
    t.kind === 'return' && t.returnDestination
      ? `Returned to: ${t.returnDestination}${t.docketNumber ? ` · Docket ${t.docketNumber}` : ''}`
      : '',
    t.kind === 'intake' && (t.supplier || t.invoiceNumber)
      ? `Supplier: ${t.supplier ?? ''}${t.invoiceNumber ? ` · Invoice ${t.invoiceNumber}` : ''}`
      : '',
    t.reason ? `Reason: ${REASON_LABELS[t.reason]}` : '',
    t.leakTestPerformed !== undefined
      ? `Leak test performed: ${t.leakTestPerformed ? 'Yes' : 'No'}`
      : '',
    techLine ? `Technician: ${techLine}` : '',
    t.notes ? `Notes: ${t.notes}` : '',
  ]
}

function clean(lines: string[]): string {
  return lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

// A tidy, plain-text record of one transaction that a tech can share, copy,
// or email straight into a job card — no double handling.
export function transactionShareText(
  t: Transaction,
  state: AppState,
): { subject: string; body: string } {
  const block = jobBlock(t, state)
  const body = clean([
    'REFRIGERANT JOB RECORD',
    '',
    ...businessLines(t, state),
    '',
    ...block,
    '',
    'Generated by Refrigerant Handling',
  ])

  const bottle = state.bottles.find((b) => b.id === t.bottleId)
  const site = state.sites.find((s) => s.id === t.siteId)
  const amount = t.amount > 0 ? formatWeight(t.amount, state.unit) : ''
  const subject = [
    transactionLabel(t.kind),
    [amount, bottle?.refrigerantType].filter(Boolean).join(' '),
    (site ? siteLabel(site) : t.siteName) || bottle?.bottleNumber,
  ]
    .filter(Boolean)
    .join(' · ')

  return { subject, body }
}

// Bundles every job logged on a given local calendar day (default: today,
// in the business timezone) into one shareable document. Returns null when
// there's nothing to share for that day.
export function dayShareText(
  transactions: Transaction[],
  state: AppState,
  day: string = localDateTimeInput(new Date(), state.location.timezone).slice(
    0,
    10,
  ),
): { subject: string; body: string } | null {
  const tz = state.location.timezone
  const jobs = transactions
    .filter(
      (t) =>
        !t.deletedAt &&
        localDateTimeInput(new Date(t.date), tz).slice(0, 10) === day,
    )
    // Chronological — the order the work was done.
    .slice()
    .sort((a, b) => a.date.localeCompare(b.date))

  if (jobs.length === 0) return null

  const header = [
    'REFRIGERANT JOBS',
    '',
    ...businessLines(jobs[0], state),
    '',
    `${day} · ${jobs.length} job${jobs.length === 1 ? '' : 's'}`,
  ]
  const blocks = jobs.flatMap((t, i) => [
    '',
    `— Job ${i + 1} —`,
    '',
    ...jobBlock(t, state),
  ])
  const body = clean([
    ...header,
    ...blocks,
    '',
    'Generated by Refrigerant Handling',
  ])

  return { subject: `Refrigerant jobs · ${day} · ${jobs.length}`, body }
}
