import type { AppState, Transaction } from './types'
import {
  REASON_LABELS,
  movementSummary,
  siteLabel,
  transactionLabel,
  transactionLoss,
} from './types'
import { formatWeight, kgToDisplay } from './units'
import { formatStampedTime } from './datetime'
import { profileFor } from './compliance'

// Builds a tidy, plain-text record of a single transaction that a tech can
// share, copy, or email straight into a job card — no double handling. It
// prefers live records (site / unit / bottle) and falls back to the values
// frozen on the row, so a record stays complete even after the linked
// bottle or site is deleted.
export function transactionShareText(
  t: Transaction,
  state: AppState,
): { subject: string; body: string } {
  const { bottles, sites, units, transactions, unit, clock, jurisdiction } = state
  const profile = profileFor(jurisdiction)
  const tz = state.location.timezone

  const bottle = bottles.find((b) => b.id === t.bottleId)
  const sourceBottle = t.sourceBottleId
    ? bottles.find((b) => b.id === t.sourceBottleId)
    : undefined
  const site = sites.find((s) => s.id === t.siteId)
  const txUnit = units.find((u) => u.id === t.unitId)
  const move = movementSummary(t, transactions, (id) =>
    sites.find((s) => s.id === id)?.name,
  )
  const loss = transactionLoss(t)

  const kind = transactionLabel(t.kind)
  const amount = t.amount > 0 ? formatWeight(t.amount, unit) : ''
  const refrigerant = bottle?.refrigerantType ?? ''
  const when = formatStampedTime(t.date, t.tz, tz, clock)
  const siteName = site ? siteLabel(site) : t.siteName

  // Equipment line: name + any manufacturer/model/serial we have.
  const equipName = txUnit?.name ?? t.unitName ?? t.equipment ?? ''
  const equipExtra = txUnit
    ? [
        [txUnit.manufacturer, txUnit.model].filter(Boolean).join(' '),
        txUnit.serial ? `S/N ${txUnit.serial}` : '',
      ]
        .filter(Boolean)
        .join(', ')
    : ''
  const equipment = equipName
    ? equipExtra
      ? `${equipName} (${equipExtra})`
      : equipName
    : ''

  const business = [
    t.businessName || state.businessName,
    t.businessAbn || state.businessAbn
      ? `${profile.businessNumberShort} ${t.businessAbn || state.businessAbn}`
      : '',
    t.arcAuthorisationNumber || state.arcAuthorisationNumber
      ? `${profile.businessAuthShort} ${
          t.arcAuthorisationNumber || state.arcAuthorisationNumber
        }`
      : '',
  ].filter(Boolean)

  const techLine =
    t.technician || t.technicianLicence
      ? [
          t.technician,
          t.technicianLicence
            ? `${profile.techLicenceShort} ${t.technicianLicence}`
            : '',
        ]
          .filter(Boolean)
          .join(' · ')
      : ''

  // Assemble. Each entry is a line (or '' to skip); blank strings drop out.
  const lines: string[] = [
    'REFRIGERANT JOB RECORD',
    '',
    ...business,
    '',
    `${kind}${amount ? ` — ${amount}` : ''}${refrigerant ? ` ${refrigerant}` : ''}`,
    when,
    '',
    siteName ? `Site: ${siteName}` : '',
    site?.address ? `Address: ${site.address}` : '',
    site?.client ? `Client: ${site.client}` : '',
    equipment ? `Equipment: ${equipment}` : '',
    bottle ? `Bottle: ${bottle.bottleNumber} (${bottle.refrigerantType})` : '',
    sourceBottle ? `From bottle: ${sourceBottle.bottleNumber}` : '',
    move ? `Movement: ${move.from} → ${move.to}` : '',
    t.amount > 0
      ? `Bottle gross: ${kgToDisplay(t.weightBefore, unit).toFixed(2)} → ${formatWeight(t.weightAfter, unit)}`
      : '',
    loss > 0 ? `Loss: ${formatWeight(loss, unit)}` : '',
    t.kind === 'return' && t.returnDestination
      ? `Returned to: ${t.returnDestination}${t.docketNumber ? ` · Docket ${t.docketNumber}` : ''}`
      : '',
    t.kind === 'intake' && (t.supplier || t.invoiceNumber)
      ? `Supplier: ${t.supplier ?? ''}${t.invoiceNumber ? ` · Invoice ${t.invoiceNumber}` : ''}`
      : '',
    t.reason ? `Reason: ${REASON_LABELS[t.reason]}` : '',
    t.leakTestPerformed !== undefined
      ? `Leak test performed: ${t.leakTestPerformed ? 'Yes' : 'No'}`
      : '',
    '',
    techLine ? `Technician: ${techLine}` : '',
    t.notes ? `Notes: ${t.notes}` : '',
    '',
    'Generated by Refrigerant Handling',
  ]

  // Collapse runs of blank lines so optional sections don't leave gaps.
  const body = lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()

  const subjectBits = [
    kind,
    [amount, refrigerant].filter(Boolean).join(' '),
    siteName || bottle?.bottleNumber,
  ].filter(Boolean)
  const subject = subjectBits.join(' · ')

  return { subject, body }
}
